/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as InstructorRouteRouteImport } from './routes/instructor/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as StudentRouteRouteImport } from './routes/student/route'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as InstructorDashboardRouteImport } from './routes/instructor/dashboard'
import { Route as InstructorEvaluationsRouteImport } from './routes/instructor/evaluations'
import { Route as InstructorGroupsRouteImport } from './routes/instructor/groups'
import { Route as InstructorProfileRouteImport } from './routes/instructor/profile'
import { Route as InstructorStudentsRouteImport } from './routes/instructor/students'
import { Route as StudentDashboardRouteImport } from './routes/student/dashboard'
import { Route as StudentEvaluationRouteImport } from './routes/student/evaluation'
import { Route as StudentEvidencesRouteImport } from './routes/student/evidences'
import { Route as StudentJourneyRouteImport } from './routes/student/journey'
import { Route as StudentProfileRouteImport } from './routes/student/profile'
import { Route as StudentProgressRouteImport } from './routes/student/progress'
import { Route as StudentRecordsRouteImport } from './routes/student/records'
import { Route as InstructorClassesIndexRouteImport } from './routes/instructor/classes.index'
import { Route as InstructorClassesClassIdRouteImport } from './routes/instructor/classes.$classId'
import { Route as StudentMissionsIndexRouteImport } from './routes/student/missions.index'
import { Route as StudentMissionsCodeRouteImport } from './routes/student/missions.$code'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorRouteRoute = InstructorRouteRouteImport.update({
  id: '/instructor',
  path: '/instructor',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRouteRoute = StudentRouteRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorDashboardRoute = InstructorDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => InstructorRouteRoute,
} as any)
const InstructorEvaluationsRoute = InstructorEvaluationsRouteImport.update({
  id: '/evaluations',
  path: '/evaluations',
  getParentRoute: () => InstructorRouteRoute,
} as any)
const InstructorGroupsRoute = InstructorGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => InstructorRouteRoute,
} as any)
const InstructorProfileRoute = InstructorProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => InstructorRouteRoute,
} as any)
const InstructorStudentsRoute = InstructorStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => InstructorRouteRoute,
} as any)
const StudentDashboardRoute = StudentDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => StudentRouteRoute,
} as any)
const StudentEvaluationRoute = StudentEvaluationRouteImport.update({
  id: '/evaluation',
  path: '/evaluation',
  getParentRoute: () => StudentRouteRoute,
} as any)
const StudentEvidencesRoute = StudentEvidencesRouteImport.update({
  id: '/evidences',
  path: '/evidences',
  getParentRoute: () => StudentRouteRoute,
} as any)
const StudentJourneyRoute = StudentJourneyRouteImport.update({
  id: '/journey',
  path: '/journey',
  getParentRoute: () => StudentRouteRoute,
} as any)
const StudentProfileRoute = StudentProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => StudentRouteRoute,
} as any)
const StudentProgressRoute = StudentProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => StudentRouteRoute,
} as any)
const StudentRecordsRoute = StudentRecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => StudentRouteRoute,
} as any)
const InstructorClassesIndexRoute = InstructorClassesIndexRouteImport.update({
  id: '/classes/',
  path: '/classes/',
  getParentRoute: () => InstructorRouteRoute,
} as any)
const InstructorClassesClassIdRoute =
  InstructorClassesClassIdRouteImport.update({
    id: '/classes/$classId',
    path: '/classes/$classId',
    getParentRoute: () => InstructorRouteRoute,
  } as any)
const StudentMissionsIndexRoute = StudentMissionsIndexRouteImport.update({
  id: '/missions/',
  path: '/missions/',
  getParentRoute: () => StudentRouteRoute,
} as any)
const StudentMissionsCodeRoute = StudentMissionsCodeRouteImport.update({
  id: '/missions/$code',
  path: '/missions/$code',
  getParentRoute: () => StudentRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/instructor': typeof InstructorRouteRouteWithChildren
  '/student': typeof StudentRouteRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/instructor/dashboard': typeof InstructorDashboardRoute
  '/instructor/evaluations': typeof InstructorEvaluationsRoute
  '/instructor/groups': typeof InstructorGroupsRoute
  '/instructor/profile': typeof InstructorProfileRoute
  '/instructor/students': typeof InstructorStudentsRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/evaluation': typeof StudentEvaluationRoute
  '/student/evidences': typeof StudentEvidencesRoute
  '/student/journey': typeof StudentJourneyRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/progress': typeof StudentProgressRoute
  '/student/records': typeof StudentRecordsRoute
  '/instructor/classes/$classId': typeof InstructorClassesClassIdRoute
  '/student/missions/$code': typeof StudentMissionsCodeRoute
  '/instructor/classes/': typeof InstructorClassesIndexRoute
  '/student/missions/': typeof StudentMissionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/instructor': typeof InstructorRouteRouteWithChildren
  '/student': typeof StudentRouteRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/instructor/dashboard': typeof InstructorDashboardRoute
  '/instructor/evaluations': typeof InstructorEvaluationsRoute
  '/instructor/groups': typeof InstructorGroupsRoute
  '/instructor/profile': typeof InstructorProfileRoute
  '/instructor/students': typeof InstructorStudentsRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/evaluation': typeof StudentEvaluationRoute
  '/student/evidences': typeof StudentEvidencesRoute
  '/student/journey': typeof StudentJourneyRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/progress': typeof StudentProgressRoute
  '/student/records': typeof StudentRecordsRoute
  '/instructor/classes/$classId': typeof InstructorClassesClassIdRoute
  '/student/missions/$code': typeof StudentMissionsCodeRoute
  '/instructor/classes': typeof InstructorClassesIndexRoute
  '/student/missions': typeof StudentMissionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/instructor': typeof InstructorRouteRouteWithChildren
  '/student': typeof StudentRouteRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/instructor/dashboard': typeof InstructorDashboardRoute
  '/instructor/evaluations': typeof InstructorEvaluationsRoute
  '/instructor/groups': typeof InstructorGroupsRoute
  '/instructor/profile': typeof InstructorProfileRoute
  '/instructor/students': typeof InstructorStudentsRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/evaluation': typeof StudentEvaluationRoute
  '/student/evidences': typeof StudentEvidencesRoute
  '/student/journey': typeof StudentJourneyRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/progress': typeof StudentProgressRoute
  '/student/records': typeof StudentRecordsRoute
  '/instructor/classes/$classId': typeof InstructorClassesClassIdRoute
  '/student/missions/$code': typeof StudentMissionsCodeRoute
  '/instructor/classes/': typeof InstructorClassesIndexRoute
  '/student/missions/': typeof StudentMissionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/instructor'
    | '/student'
    | '/dashboard'
    | '/login'
    | '/reset-password'
    | '/auth/callback'
    | '/instructor/dashboard'
    | '/instructor/evaluations'
    | '/instructor/groups'
    | '/instructor/profile'
    | '/instructor/students'
    | '/student/dashboard'
    | '/student/evaluation'
    | '/student/evidences'
    | '/student/journey'
    | '/student/profile'
    | '/student/progress'
    | '/student/records'
    | '/instructor/classes/$classId'
    | '/student/missions/$code'
    | '/instructor/classes/'
    | '/student/missions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/instructor'
    | '/student'
    | '/dashboard'
    | '/login'
    | '/reset-password'
    | '/auth/callback'
    | '/instructor/dashboard'
    | '/instructor/evaluations'
    | '/instructor/groups'
    | '/instructor/profile'
    | '/instructor/students'
    | '/student/dashboard'
    | '/student/evaluation'
    | '/student/evidences'
    | '/student/journey'
    | '/student/profile'
    | '/student/progress'
    | '/student/records'
    | '/instructor/classes/$classId'
    | '/student/missions/$code'
    | '/instructor/classes'
    | '/student/missions'
  id:
    | '__root__'
    | '/'
    | '/instructor'
    | '/student'
    | '/dashboard'
    | '/login'
    | '/reset-password'
    | '/auth/callback'
    | '/instructor/dashboard'
    | '/instructor/evaluations'
    | '/instructor/groups'
    | '/instructor/profile'
    | '/instructor/students'
    | '/student/dashboard'
    | '/student/evaluation'
    | '/student/evidences'
    | '/student/journey'
    | '/student/profile'
    | '/student/progress'
    | '/student/records'
    | '/instructor/classes/$classId'
    | '/student/missions/$code'
    | '/instructor/classes/'
    | '/student/missions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InstructorRouteRoute: typeof InstructorRouteRouteWithChildren
  StudentRouteRoute: typeof StudentRouteRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructor': {
      id: '/instructor'
      path: '/instructor'
      fullPath: '/instructor'
      preLoaderRoute: typeof InstructorRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructor/dashboard': {
      id: '/instructor/dashboard'
      path: '/dashboard'
      fullPath: '/instructor/dashboard'
      preLoaderRoute: typeof InstructorDashboardRouteImport
      parentRoute: typeof InstructorRouteRoute
    }
    '/instructor/evaluations': {
      id: '/instructor/evaluations'
      path: '/evaluations'
      fullPath: '/instructor/evaluations'
      preLoaderRoute: typeof InstructorEvaluationsRouteImport
      parentRoute: typeof InstructorRouteRoute
    }
    '/instructor/groups': {
      id: '/instructor/groups'
      path: '/groups'
      fullPath: '/instructor/groups'
      preLoaderRoute: typeof InstructorGroupsRouteImport
      parentRoute: typeof InstructorRouteRoute
    }
    '/instructor/profile': {
      id: '/instructor/profile'
      path: '/profile'
      fullPath: '/instructor/profile'
      preLoaderRoute: typeof InstructorProfileRouteImport
      parentRoute: typeof InstructorRouteRoute
    }
    '/instructor/students': {
      id: '/instructor/students'
      path: '/students'
      fullPath: '/instructor/students'
      preLoaderRoute: typeof InstructorStudentsRouteImport
      parentRoute: typeof InstructorRouteRoute
    }
    '/student/dashboard': {
      id: '/student/dashboard'
      path: '/dashboard'
      fullPath: '/student/dashboard'
      preLoaderRoute: typeof StudentDashboardRouteImport
      parentRoute: typeof StudentRouteRoute
    }
    '/student/evaluation': {
      id: '/student/evaluation'
      path: '/evaluation'
      fullPath: '/student/evaluation'
      preLoaderRoute: typeof StudentEvaluationRouteImport
      parentRoute: typeof StudentRouteRoute
    }
    '/student/evidences': {
      id: '/student/evidences'
      path: '/evidences'
      fullPath: '/student/evidences'
      preLoaderRoute: typeof StudentEvidencesRouteImport
      parentRoute: typeof StudentRouteRoute
    }
    '/student/journey': {
      id: '/student/journey'
      path: '/journey'
      fullPath: '/student/journey'
      preLoaderRoute: typeof StudentJourneyRouteImport
      parentRoute: typeof StudentRouteRoute
    }
    '/student/profile': {
      id: '/student/profile'
      path: '/profile'
      fullPath: '/student/profile'
      preLoaderRoute: typeof StudentProfileRouteImport
      parentRoute: typeof StudentRouteRoute
    }
    '/student/progress': {
      id: '/student/progress'
      path: '/progress'
      fullPath: '/student/progress'
      preLoaderRoute: typeof StudentProgressRouteImport
      parentRoute: typeof StudentRouteRoute
    }
    '/student/records': {
      id: '/student/records'
      path: '/records'
      fullPath: '/student/records'
      preLoaderRoute: typeof StudentRecordsRouteImport
      parentRoute: typeof StudentRouteRoute
    }
    '/instructor/classes/': {
      id: '/instructor/classes/'
      path: '/classes'
      fullPath: '/instructor/classes/'
      preLoaderRoute: typeof InstructorClassesIndexRouteImport
      parentRoute: typeof InstructorRouteRoute
    }
    '/instructor/classes/$classId': {
      id: '/instructor/classes/$classId'
      path: '/classes/$classId'
      fullPath: '/instructor/classes/$classId'
      preLoaderRoute: typeof InstructorClassesClassIdRouteImport
      parentRoute: typeof InstructorRouteRoute
    }
    '/student/missions/': {
      id: '/student/missions/'
      path: '/missions'
      fullPath: '/student/missions/'
      preLoaderRoute: typeof StudentMissionsIndexRouteImport
      parentRoute: typeof StudentRouteRoute
    }
    '/student/missions/$code': {
      id: '/student/missions/$code'
      path: '/missions/$code'
      fullPath: '/student/missions/$code'
      preLoaderRoute: typeof StudentMissionsCodeRouteImport
      parentRoute: typeof StudentRouteRoute
    }
  }
}

interface InstructorRouteRouteChildren {
  InstructorDashboardRoute: typeof InstructorDashboardRoute
  InstructorEvaluationsRoute: typeof InstructorEvaluationsRoute
  InstructorGroupsRoute: typeof InstructorGroupsRoute
  InstructorProfileRoute: typeof InstructorProfileRoute
  InstructorStudentsRoute: typeof InstructorStudentsRoute
  InstructorClassesClassIdRoute: typeof InstructorClassesClassIdRoute
  InstructorClassesIndexRoute: typeof InstructorClassesIndexRoute
}

const InstructorRouteRouteChildren: InstructorRouteRouteChildren = {
  InstructorDashboardRoute: InstructorDashboardRoute,
  InstructorEvaluationsRoute: InstructorEvaluationsRoute,
  InstructorGroupsRoute: InstructorGroupsRoute,
  InstructorProfileRoute: InstructorProfileRoute,
  InstructorStudentsRoute: InstructorStudentsRoute,
  InstructorClassesClassIdRoute: InstructorClassesClassIdRoute,
  InstructorClassesIndexRoute: InstructorClassesIndexRoute,
}

const InstructorRouteRouteWithChildren = InstructorRouteRoute._addFileChildren(
  InstructorRouteRouteChildren,
)

interface StudentRouteRouteChildren {
  StudentDashboardRoute: typeof StudentDashboardRoute
  StudentEvaluationRoute: typeof StudentEvaluationRoute
  StudentEvidencesRoute: typeof StudentEvidencesRoute
  StudentJourneyRoute: typeof StudentJourneyRoute
  StudentProfileRoute: typeof StudentProfileRoute
  StudentProgressRoute: typeof StudentProgressRoute
  StudentRecordsRoute: typeof StudentRecordsRoute
  StudentMissionsCodeRoute: typeof StudentMissionsCodeRoute
  StudentMissionsIndexRoute: typeof StudentMissionsIndexRoute
}

const StudentRouteRouteChildren: StudentRouteRouteChildren = {
  StudentDashboardRoute: StudentDashboardRoute,
  StudentEvaluationRoute: StudentEvaluationRoute,
  StudentEvidencesRoute: StudentEvidencesRoute,
  StudentJourneyRoute: StudentJourneyRoute,
  StudentProfileRoute: StudentProfileRoute,
  StudentProgressRoute: StudentProgressRoute,
  StudentRecordsRoute: StudentRecordsRoute,
  StudentMissionsCodeRoute: StudentMissionsCodeRoute,
  StudentMissionsIndexRoute: StudentMissionsIndexRoute,
}

const StudentRouteRouteWithChildren = StudentRouteRoute._addFileChildren(
  StudentRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InstructorRouteRoute: InstructorRouteRouteWithChildren,
  StudentRouteRoute: StudentRouteRouteWithChildren,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
