/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as InstructorRouteRouteImport } from './routes/instructor/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as StudentRouteRouteImport } from './routes/student/route'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as InstructorCafeRouteImport } from './routes/instructor/cafe'
import { Route as InstructorDashboardRouteImport } from './routes/instructor/dashboard'
import { Route as InstructorDossierRouteImport } from './routes/instructor/dossier'
import { Route as InstructorEvaluationsRouteImport } from './routes/instructor/evaluations'
import { Route as InstructorFeaturesRouteImport } from './routes/instructor/features'
import { Route as InstructorFinalRouteImport } from './routes/instructor/final'
import { Route as InstructorGamificationRouteImport } from './routes/instructor/gamification'
import { Route as InstructorGroupsRouteImport } from './routes/instructor/groups'
import { Route as InstructorInventoryRouteImport } from './routes/instructor/inventory'
import { Route as InstructorPortfoliosRouteImport } from './routes/instructor/portfolios'
import { Route as InstructorProfileRouteImport } from './routes/instructor/profile'
import { Route as InstructorQaRouteImport } from './routes/instructor/qa'
import { Route as InstructorRecoveryRouteImport } from './routes/instructor/recovery'
import { Route as InstructorReportsRouteImport } from './routes/instructor/reports'
import { Route as StudentDashboardRouteImport } from './routes/student/dashboard'
import { Route as StudentEvaluationRouteImport } from './routes/student/evaluation'
import { Route as StudentEvidencesRouteImport } from './routes/student/evidences'
import { Route as StudentInventoryRouteImport } from './routes/student/inventory'
import { Route as StudentJourneyRouteImport } from './routes/student/journey'
import { Route as StudentPortfolioRouteImport } from './routes/student/portfolio'
import { Route as StudentProfileRouteImport } from './routes/student/profile'
import { Route as StudentProgressRouteImport } from './routes/student/progress'
import { Route as StudentQaRouteImport } from './routes/student/qa'
import { Route as StudentRankingRouteImport } from './routes/student/ranking'
import { Route as StudentRecordsRouteImport } from './routes/student/records'
import { Route as InstructorClassesIndexRouteImport } from './routes/instructor/classes.index'
import { Route as InstructorClassesClassIdRouteImport } from './routes/instructor/classes.$classId'
import { Route as InstructorMissionsIndexRouteImport } from './routes/instructor/missions.index'
import { Route as InstructorMissionsMissionIdRouteImport } from './routes/instructor/missions.$missionId'
import { Route as InstructorStudentsIndexRouteImport } from './routes/instructor/students.index'
import { Route as InstructorStudentsStudentIdRouteImport } from './routes/instructor/students.$studentId'
import { Route as InstructorSubmissionsIndexRouteImport } from './routes/instructor/submissions.index'
import { Route as StudentActivitiesIndexRouteImport } from './routes/student/activities.index'
import { Route as StudentActivitiesMissionIdRouteImport } from './routes/student/activities.$missionId'
import { Route as StudentCafeIndexRouteImport } from './routes/student/cafe.index'
import { Route as StudentCafeGroupIdRouteImport } from './routes/student/cafe.$groupId'
import { Route as StudentMissionsIndexRouteImport } from './routes/student/missions.index'
import { Route as StudentMissionsCodeRouteImport } from './routes/student/missions.$code'
import { Route as StudentMissionsRunIdRouteImport } from './routes/student/missions.$runId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorRouteRoute = InstructorRouteRouteImport.update({
  id: '/instructor',
  path: '/instructor',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRouteRoute = StudentRouteRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorCafeRoute = InstructorCafeRouteImport.update({
  id: '/cafe',
  path: '/cafe',
  getParentRoute: () => InstructorRouteRoute,
} as any)
const InstructorDashboardRoute = InstructorDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => InstructorRouteRoute,
} as any)
const InstructorDossierRoute = InstructorDossierRouteImport.update({
  id: '/dossier',
  path: '/dossier',
  getParentRoute: () => InstructorRouteRoute,
} as any)
const InstructorEvaluationsRoute = InstructorEvaluationsRouteImport.update({
  id: '/evaluations',
  path: '/evaluations',
  getParentRoute: () => InstructorRouteRoute,
} as any)
const InstructorFeaturesRoute = InstructorFeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => InstructorRouteRoute,
} as any)
const InstructorFinalRoute = InstructorFinalRouteImport.update({
  id: '/final',
  path: '/final',
  getParentRoute: () => InstructorRouteRoute,
} as any)
const InstructorGamificationRoute = InstructorGamificationRouteImport.update({
  id: '/gamification',
  path: '/gamification',
  getParentRoute: () => InstructorRouteRoute,
} as any)
const InstructorGroupsRoute = InstructorGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => InstructorRouteRoute,
} as any)
const InstructorInventoryRoute = InstructorInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => InstructorRouteRoute,
} as any)
const InstructorPortfoliosRoute = InstructorPortfoliosRouteImport.update({
  id: '/portfolios',
  path: '/portfolios',
  getParentRoute: () => InstructorRouteRoute,
} as any)
const InstructorProfileRoute = InstructorProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => InstructorRouteRoute,
} as any)
const InstructorQaRoute = InstructorQaRouteImport.update({
  id: '/qa',
  path: '/qa',
  getParentRoute: () => InstructorRouteRoute,
} as any)
const InstructorRecoveryRoute = InstructorRecoveryRouteImport.update({
  id: '/recovery',
  path: '/recovery',
  getParentRoute: () => InstructorRouteRoute,
} as any)
const InstructorReportsRoute = InstructorReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => InstructorRouteRoute,
} as any)
const StudentDashboardRoute = StudentDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => StudentRouteRoute,
} as any)
const StudentEvaluationRoute = StudentEvaluationRouteImport.update({
  id: '/evaluation',
  path: '/evaluation',
  getParentRoute: () => StudentRouteRoute,
} as any)
const StudentEvidencesRoute = StudentEvidencesRouteImport.update({
  id: '/evidences',
  path: '/evidences',
  getParentRoute: () => StudentRouteRoute,
} as any)
const StudentInventoryRoute = StudentInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => StudentRouteRoute,
} as any)
const StudentJourneyRoute = StudentJourneyRouteImport.update({
  id: '/journey',
  path: '/journey',
  getParentRoute: () => StudentRouteRoute,
} as any)
const StudentPortfolioRoute = StudentPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => StudentRouteRoute,
} as any)
const StudentProfileRoute = StudentProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => StudentRouteRoute,
} as any)
const StudentProgressRoute = StudentProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => StudentRouteRoute,
} as any)
const StudentQaRoute = StudentQaRouteImport.update({
  id: '/qa',
  path: '/qa',
  getParentRoute: () => StudentRouteRoute,
} as any)
const StudentRankingRoute = StudentRankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => StudentRouteRoute,
} as any)
const StudentRecordsRoute = StudentRecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => StudentRouteRoute,
} as any)
const InstructorClassesIndexRoute = InstructorClassesIndexRouteImport.update({
  id: '/classes/',
  path: '/classes/',
  getParentRoute: () => InstructorRouteRoute,
} as any)
const InstructorClassesClassIdRoute =
  InstructorClassesClassIdRouteImport.update({
    id: '/classes/$classId',
    path: '/classes/$classId',
    getParentRoute: () => InstructorRouteRoute,
  } as any)
const InstructorMissionsIndexRoute = InstructorMissionsIndexRouteImport.update({
  id: '/missions/',
  path: '/missions/',
  getParentRoute: () => InstructorRouteRoute,
} as any)
const InstructorMissionsMissionIdRoute =
  InstructorMissionsMissionIdRouteImport.update({
    id: '/missions/$missionId',
    path: '/missions/$missionId',
    getParentRoute: () => InstructorRouteRoute,
  } as any)
const InstructorStudentsIndexRoute = InstructorStudentsIndexRouteImport.update({
  id: '/students/',
  path: '/students/',
  getParentRoute: () => InstructorRouteRoute,
} as any)
const InstructorStudentsStudentIdRoute =
  InstructorStudentsStudentIdRouteImport.update({
    id: '/students/$studentId',
    path: '/students/$studentId',
    getParentRoute: () => InstructorRouteRoute,
  } as any)
const InstructorSubmissionsIndexRoute =
  InstructorSubmissionsIndexRouteImport.update({
    id: '/submissions/',
    path: '/submissions/',
    getParentRoute: () => InstructorRouteRoute,
  } as any)
const StudentActivitiesIndexRoute = StudentActivitiesIndexRouteImport.update({
  id: '/activities/',
  path: '/activities/',
  getParentRoute: () => StudentRouteRoute,
} as any)
const StudentActivitiesMissionIdRoute =
  StudentActivitiesMissionIdRouteImport.update({
    id: '/activities/$missionId',
    path: '/activities/$missionId',
    getParentRoute: () => StudentRouteRoute,
  } as any)
const StudentCafeIndexRoute = StudentCafeIndexRouteImport.update({
  id: '/cafe/',
  path: '/cafe/',
  getParentRoute: () => StudentRouteRoute,
} as any)
const StudentCafeGroupIdRoute = StudentCafeGroupIdRouteImport.update({
  id: '/cafe/$groupId',
  path: '/cafe/$groupId',
  getParentRoute: () => StudentRouteRoute,
} as any)
const StudentMissionsIndexRoute = StudentMissionsIndexRouteImport.update({
  id: '/missions/',
  path: '/missions/',
  getParentRoute: () => StudentRouteRoute,
} as any)
const StudentMissionsCodeRoute = StudentMissionsCodeRouteImport.update({
  id: '/missions/$code',
  path: '/missions/$code',
  getParentRoute: () => StudentRouteRoute,
} as any)
const StudentMissionsRunIdRoute = StudentMissionsRunIdRouteImport.update({
  id: '/missions/$runId',
  path: '/missions/$runId',
  getParentRoute: () => StudentRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/instructor': typeof InstructorRouteRouteWithChildren
  '/student': typeof StudentRouteRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/instructor/cafe': typeof InstructorCafeRoute
  '/instructor/dashboard': typeof InstructorDashboardRoute
  '/instructor/dossier': typeof InstructorDossierRoute
  '/instructor/evaluations': typeof InstructorEvaluationsRoute
  '/instructor/features': typeof InstructorFeaturesRoute
  '/instructor/final': typeof InstructorFinalRoute
  '/instructor/gamification': typeof InstructorGamificationRoute
  '/instructor/groups': typeof InstructorGroupsRoute
  '/instructor/inventory': typeof InstructorInventoryRoute
  '/instructor/portfolios': typeof InstructorPortfoliosRoute
  '/instructor/profile': typeof InstructorProfileRoute
  '/instructor/qa': typeof InstructorQaRoute
  '/instructor/recovery': typeof InstructorRecoveryRoute
  '/instructor/reports': typeof InstructorReportsRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/evaluation': typeof StudentEvaluationRoute
  '/student/evidences': typeof StudentEvidencesRoute
  '/student/inventory': typeof StudentInventoryRoute
  '/student/journey': typeof StudentJourneyRoute
  '/student/portfolio': typeof StudentPortfolioRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/progress': typeof StudentProgressRoute
  '/student/qa': typeof StudentQaRoute
  '/student/ranking': typeof StudentRankingRoute
  '/student/records': typeof StudentRecordsRoute
  '/instructor/classes/$classId': typeof InstructorClassesClassIdRoute
  '/instructor/missions/$missionId': typeof InstructorMissionsMissionIdRoute
  '/instructor/students/$studentId': typeof InstructorStudentsStudentIdRoute
  '/student/activities/$missionId': typeof StudentActivitiesMissionIdRoute
  '/student/cafe/$groupId': typeof StudentCafeGroupIdRoute
  '/student/missions/$code': typeof StudentMissionsCodeRoute
  '/student/missions/$runId': typeof StudentMissionsRunIdRoute
  '/instructor/classes/': typeof InstructorClassesIndexRoute
  '/instructor/missions/': typeof InstructorMissionsIndexRoute
  '/instructor/students/': typeof InstructorStudentsIndexRoute
  '/instructor/submissions/': typeof InstructorSubmissionsIndexRoute
  '/student/activities/': typeof StudentActivitiesIndexRoute
  '/student/cafe/': typeof StudentCafeIndexRoute
  '/student/missions/': typeof StudentMissionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/instructor': typeof InstructorRouteRouteWithChildren
  '/student': typeof StudentRouteRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/instructor/cafe': typeof InstructorCafeRoute
  '/instructor/dashboard': typeof InstructorDashboardRoute
  '/instructor/dossier': typeof InstructorDossierRoute
  '/instructor/evaluations': typeof InstructorEvaluationsRoute
  '/instructor/features': typeof InstructorFeaturesRoute
  '/instructor/final': typeof InstructorFinalRoute
  '/instructor/gamification': typeof InstructorGamificationRoute
  '/instructor/groups': typeof InstructorGroupsRoute
  '/instructor/inventory': typeof InstructorInventoryRoute
  '/instructor/portfolios': typeof InstructorPortfoliosRoute
  '/instructor/profile': typeof InstructorProfileRoute
  '/instructor/qa': typeof InstructorQaRoute
  '/instructor/recovery': typeof InstructorRecoveryRoute
  '/instructor/reports': typeof InstructorReportsRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/evaluation': typeof StudentEvaluationRoute
  '/student/evidences': typeof StudentEvidencesRoute
  '/student/inventory': typeof StudentInventoryRoute
  '/student/journey': typeof StudentJourneyRoute
  '/student/portfolio': typeof StudentPortfolioRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/progress': typeof StudentProgressRoute
  '/student/qa': typeof StudentQaRoute
  '/student/ranking': typeof StudentRankingRoute
  '/student/records': typeof StudentRecordsRoute
  '/instructor/classes/$classId': typeof InstructorClassesClassIdRoute
  '/instructor/missions/$missionId': typeof InstructorMissionsMissionIdRoute
  '/instructor/students/$studentId': typeof InstructorStudentsStudentIdRoute
  '/student/activities/$missionId': typeof StudentActivitiesMissionIdRoute
  '/student/cafe/$groupId': typeof StudentCafeGroupIdRoute
  '/student/missions/$code': typeof StudentMissionsCodeRoute
  '/student/missions/$runId': typeof StudentMissionsRunIdRoute
  '/instructor/classes': typeof InstructorClassesIndexRoute
  '/instructor/missions': typeof InstructorMissionsIndexRoute
  '/instructor/students': typeof InstructorStudentsIndexRoute
  '/instructor/submissions': typeof InstructorSubmissionsIndexRoute
  '/student/activities': typeof StudentActivitiesIndexRoute
  '/student/cafe': typeof StudentCafeIndexRoute
  '/student/missions': typeof StudentMissionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/instructor': typeof InstructorRouteRouteWithChildren
  '/student': typeof StudentRouteRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/instructor/cafe': typeof InstructorCafeRoute
  '/instructor/dashboard': typeof InstructorDashboardRoute
  '/instructor/dossier': typeof InstructorDossierRoute
  '/instructor/evaluations': typeof InstructorEvaluationsRoute
  '/instructor/features': typeof InstructorFeaturesRoute
  '/instructor/final': typeof InstructorFinalRoute
  '/instructor/gamification': typeof InstructorGamificationRoute
  '/instructor/groups': typeof InstructorGroupsRoute
  '/instructor/inventory': typeof InstructorInventoryRoute
  '/instructor/portfolios': typeof InstructorPortfoliosRoute
  '/instructor/profile': typeof InstructorProfileRoute
  '/instructor/qa': typeof InstructorQaRoute
  '/instructor/recovery': typeof InstructorRecoveryRoute
  '/instructor/reports': typeof InstructorReportsRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/evaluation': typeof StudentEvaluationRoute
  '/student/evidences': typeof StudentEvidencesRoute
  '/student/inventory': typeof StudentInventoryRoute
  '/student/journey': typeof StudentJourneyRoute
  '/student/portfolio': typeof StudentPortfolioRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/progress': typeof StudentProgressRoute
  '/student/qa': typeof StudentQaRoute
  '/student/ranking': typeof StudentRankingRoute
  '/student/records': typeof StudentRecordsRoute
  '/instructor/classes/$classId': typeof InstructorClassesClassIdRoute
  '/instructor/missions/$missionId': typeof InstructorMissionsMissionIdRoute
  '/instructor/students/$studentId': typeof InstructorStudentsStudentIdRoute
  '/student/activities/$missionId': typeof StudentActivitiesMissionIdRoute
  '/student/cafe/$groupId': typeof StudentCafeGroupIdRoute
  '/student/missions/$code': typeof StudentMissionsCodeRoute
  '/student/missions/$runId': typeof StudentMissionsRunIdRoute
  '/instructor/classes/': typeof InstructorClassesIndexRoute
  '/instructor/missions/': typeof InstructorMissionsIndexRoute
  '/instructor/students/': typeof InstructorStudentsIndexRoute
  '/instructor/submissions/': typeof InstructorSubmissionsIndexRoute
  '/student/activities/': typeof StudentActivitiesIndexRoute
  '/student/cafe/': typeof StudentCafeIndexRoute
  '/student/missions/': typeof StudentMissionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/instructor'
    | '/student'
    | '/dashboard'
    | '/login'
    | '/reset-password'
    | '/auth/callback'
    | '/instructor/cafe'
    | '/instructor/dashboard'
    | '/instructor/dossier'
    | '/instructor/evaluations'
    | '/instructor/features'
    | '/instructor/final'
    | '/instructor/gamification'
    | '/instructor/groups'
    | '/instructor/inventory'
    | '/instructor/portfolios'
    | '/instructor/profile'
    | '/instructor/qa'
    | '/instructor/recovery'
    | '/instructor/reports'
    | '/student/dashboard'
    | '/student/evaluation'
    | '/student/evidences'
    | '/student/inventory'
    | '/student/journey'
    | '/student/portfolio'
    | '/student/profile'
    | '/student/progress'
    | '/student/qa'
    | '/student/ranking'
    | '/student/records'
    | '/instructor/classes/$classId'
    | '/instructor/missions/$missionId'
    | '/instructor/students/$studentId'
    | '/student/activities/$missionId'
    | '/student/cafe/$groupId'
    | '/student/missions/$code'
    | '/student/missions/$runId'
    | '/instructor/classes/'
    | '/instructor/missions/'
    | '/instructor/students/'
    | '/instructor/submissions/'
    | '/student/activities/'
    | '/student/cafe/'
    | '/student/missions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/instructor'
    | '/student'
    | '/dashboard'
    | '/login'
    | '/reset-password'
    | '/auth/callback'
    | '/instructor/cafe'
    | '/instructor/dashboard'
    | '/instructor/dossier'
    | '/instructor/evaluations'
    | '/instructor/features'
    | '/instructor/final'
    | '/instructor/gamification'
    | '/instructor/groups'
    | '/instructor/inventory'
    | '/instructor/portfolios'
    | '/instructor/profile'
    | '/instructor/qa'
    | '/instructor/recovery'
    | '/instructor/reports'
    | '/student/dashboard'
    | '/student/evaluation'
    | '/student/evidences'
    | '/student/inventory'
    | '/student/journey'
    | '/student/portfolio'
    | '/student/profile'
    | '/student/progress'
    | '/student/qa'
    | '/student/ranking'
    | '/student/records'
    | '/instructor/classes/$classId'
    | '/instructor/missions/$missionId'
    | '/instructor/students/$studentId'
    | '/student/activities/$missionId'
    | '/student/cafe/$groupId'
    | '/student/missions/$code'
    | '/student/missions/$runId'
    | '/instructor/classes'
    | '/instructor/missions'
    | '/instructor/students'
    | '/instructor/submissions'
    | '/student/activities'
    | '/student/cafe'
    | '/student/missions'
  id:
    | '__root__'
    | '/'
    | '/instructor'
    | '/student'
    | '/dashboard'
    | '/login'
    | '/reset-password'
    | '/auth/callback'
    | '/instructor/cafe'
    | '/instructor/dashboard'
    | '/instructor/dossier'
    | '/instructor/evaluations'
    | '/instructor/features'
    | '/instructor/final'
    | '/instructor/gamification'
    | '/instructor/groups'
    | '/instructor/inventory'
    | '/instructor/portfolios'
    | '/instructor/profile'
    | '/instructor/qa'
    | '/instructor/recovery'
    | '/instructor/reports'
    | '/student/dashboard'
    | '/student/evaluation'
    | '/student/evidences'
    | '/student/inventory'
    | '/student/journey'
    | '/student/portfolio'
    | '/student/profile'
    | '/student/progress'
    | '/student/qa'
    | '/student/ranking'
    | '/student/records'
    | '/instructor/classes/$classId'
    | '/instructor/missions/$missionId'
    | '/instructor/students/$studentId'
    | '/student/activities/$missionId'
    | '/student/cafe/$groupId'
    | '/student/missions/$code'
    | '/student/missions/$runId'
    | '/instructor/classes/'
    | '/instructor/missions/'
    | '/instructor/students/'
    | '/instructor/submissions/'
    | '/student/activities/'
    | '/student/cafe/'
    | '/student/missions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InstructorRouteRoute: typeof InstructorRouteRouteWithChildren
  StudentRouteRoute: typeof StudentRouteRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructor': {
      id: '/instructor'
      path: '/instructor'
      fullPath: '/instructor'
      preLoaderRoute: typeof InstructorRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructor/cafe': {
      id: '/instructor/cafe'
      path: '/cafe'
      fullPath: '/instructor/cafe'
      preLoaderRoute: typeof InstructorCafeRouteImport
      parentRoute: typeof InstructorRouteRoute
    }
    '/instructor/dashboard': {
      id: '/instructor/dashboard'
      path: '/dashboard'
      fullPath: '/instructor/dashboard'
      preLoaderRoute: typeof InstructorDashboardRouteImport
      parentRoute: typeof InstructorRouteRoute
    }
    '/instructor/dossier': {
      id: '/instructor/dossier'
      path: '/dossier'
      fullPath: '/instructor/dossier'
      preLoaderRoute: typeof InstructorDossierRouteImport
      parentRoute: typeof InstructorRouteRoute
    }
    '/instructor/evaluations': {
      id: '/instructor/evaluations'
      path: '/evaluations'
      fullPath: '/instructor/evaluations'
      preLoaderRoute: typeof InstructorEvaluationsRouteImport
      parentRoute: typeof InstructorRouteRoute
    }
    '/instructor/features': {
      id: '/instructor/features'
      path: '/features'
      fullPath: '/instructor/features'
      preLoaderRoute: typeof InstructorFeaturesRouteImport
      parentRoute: typeof InstructorRouteRoute
    }
    '/instructor/final': {
      id: '/instructor/final'
      path: '/final'
      fullPath: '/instructor/final'
      preLoaderRoute: typeof InstructorFinalRouteImport
      parentRoute: typeof InstructorRouteRoute
    }
    '/instructor/gamification': {
      id: '/instructor/gamification'
      path: '/gamification'
      fullPath: '/instructor/gamification'
      preLoaderRoute: typeof InstructorGamificationRouteImport
      parentRoute: typeof InstructorRouteRoute
    }
    '/instructor/groups': {
      id: '/instructor/groups'
      path: '/groups'
      fullPath: '/instructor/groups'
      preLoaderRoute: typeof InstructorGroupsRouteImport
      parentRoute: typeof InstructorRouteRoute
    }
    '/instructor/inventory': {
      id: '/instructor/inventory'
      path: '/inventory'
      fullPath: '/instructor/inventory'
      preLoaderRoute: typeof InstructorInventoryRouteImport
      parentRoute: typeof InstructorRouteRoute
    }
    '/instructor/portfolios': {
      id: '/instructor/portfolios'
      path: '/portfolios'
      fullPath: '/instructor/portfolios'
      preLoaderRoute: typeof InstructorPortfoliosRouteImport
      parentRoute: typeof InstructorRouteRoute
    }
    '/instructor/profile': {
      id: '/instructor/profile'
      path: '/profile'
      fullPath: '/instructor/profile'
      preLoaderRoute: typeof InstructorProfileRouteImport
      parentRoute: typeof InstructorRouteRoute
    }
    '/instructor/qa': {
      id: '/instructor/qa'
      path: '/qa'
      fullPath: '/instructor/qa'
      preLoaderRoute: typeof InstructorQaRouteImport
      parentRoute: typeof InstructorRouteRoute
    }
    '/instructor/recovery': {
      id: '/instructor/recovery'
      path: '/recovery'
      fullPath: '/instructor/recovery'
      preLoaderRoute: typeof InstructorRecoveryRouteImport
      parentRoute: typeof InstructorRouteRoute
    }
    '/instructor/reports': {
      id: '/instructor/reports'
      path: '/reports'
      fullPath: '/instructor/reports'
      preLoaderRoute: typeof InstructorReportsRouteImport
      parentRoute: typeof InstructorRouteRoute
    }
    '/student/dashboard': {
      id: '/student/dashboard'
      path: '/dashboard'
      fullPath: '/student/dashboard'
      preLoaderRoute: typeof StudentDashboardRouteImport
      parentRoute: typeof StudentRouteRoute
    }
    '/student/evaluation': {
      id: '/student/evaluation'
      path: '/evaluation'
      fullPath: '/student/evaluation'
      preLoaderRoute: typeof StudentEvaluationRouteImport
      parentRoute: typeof StudentRouteRoute
    }
    '/student/evidences': {
      id: '/student/evidences'
      path: '/evidences'
      fullPath: '/student/evidences'
      preLoaderRoute: typeof StudentEvidencesRouteImport
      parentRoute: typeof StudentRouteRoute
    }
    '/student/inventory': {
      id: '/student/inventory'
      path: '/inventory'
      fullPath: '/student/inventory'
      preLoaderRoute: typeof StudentInventoryRouteImport
      parentRoute: typeof StudentRouteRoute
    }
    '/student/journey': {
      id: '/student/journey'
      path: '/journey'
      fullPath: '/student/journey'
      preLoaderRoute: typeof StudentJourneyRouteImport
      parentRoute: typeof StudentRouteRoute
    }
    '/student/portfolio': {
      id: '/student/portfolio'
      path: '/portfolio'
      fullPath: '/student/portfolio'
      preLoaderRoute: typeof StudentPortfolioRouteImport
      parentRoute: typeof StudentRouteRoute
    }
    '/student/profile': {
      id: '/student/profile'
      path: '/profile'
      fullPath: '/student/profile'
      preLoaderRoute: typeof StudentProfileRouteImport
      parentRoute: typeof StudentRouteRoute
    }
    '/student/progress': {
      id: '/student/progress'
      path: '/progress'
      fullPath: '/student/progress'
      preLoaderRoute: typeof StudentProgressRouteImport
      parentRoute: typeof StudentRouteRoute
    }
    '/student/qa': {
      id: '/student/qa'
      path: '/qa'
      fullPath: '/student/qa'
      preLoaderRoute: typeof StudentQaRouteImport
      parentRoute: typeof StudentRouteRoute
    }
    '/student/ranking': {
      id: '/student/ranking'
      path: '/ranking'
      fullPath: '/student/ranking'
      preLoaderRoute: typeof StudentRankingRouteImport
      parentRoute: typeof StudentRouteRoute
    }
    '/student/records': {
      id: '/student/records'
      path: '/records'
      fullPath: '/student/records'
      preLoaderRoute: typeof StudentRecordsRouteImport
      parentRoute: typeof StudentRouteRoute
    }
    '/instructor/classes/': {
      id: '/instructor/classes/'
      path: '/classes'
      fullPath: '/instructor/classes/'
      preLoaderRoute: typeof InstructorClassesIndexRouteImport
      parentRoute: typeof InstructorRouteRoute
    }
    '/instructor/classes/$classId': {
      id: '/instructor/classes/$classId'
      path: '/classes/$classId'
      fullPath: '/instructor/classes/$classId'
      preLoaderRoute: typeof InstructorClassesClassIdRouteImport
      parentRoute: typeof InstructorRouteRoute
    }
    '/instructor/missions/': {
      id: '/instructor/missions/'
      path: '/missions'
      fullPath: '/instructor/missions/'
      preLoaderRoute: typeof InstructorMissionsIndexRouteImport
      parentRoute: typeof InstructorRouteRoute
    }
    '/instructor/missions/$missionId': {
      id: '/instructor/missions/$missionId'
      path: '/missions/$missionId'
      fullPath: '/instructor/missions/$missionId'
      preLoaderRoute: typeof InstructorMissionsMissionIdRouteImport
      parentRoute: typeof InstructorRouteRoute
    }
    '/instructor/students/': {
      id: '/instructor/students/'
      path: '/students'
      fullPath: '/instructor/students/'
      preLoaderRoute: typeof InstructorStudentsIndexRouteImport
      parentRoute: typeof InstructorRouteRoute
    }
    '/instructor/students/$studentId': {
      id: '/instructor/students/$studentId'
      path: '/students/$studentId'
      fullPath: '/instructor/students/$studentId'
      preLoaderRoute: typeof InstructorStudentsStudentIdRouteImport
      parentRoute: typeof InstructorRouteRoute
    }
    '/instructor/submissions/': {
      id: '/instructor/submissions/'
      path: '/submissions'
      fullPath: '/instructor/submissions/'
      preLoaderRoute: typeof InstructorSubmissionsIndexRouteImport
      parentRoute: typeof InstructorRouteRoute
    }
    '/student/activities/': {
      id: '/student/activities/'
      path: '/activities'
      fullPath: '/student/activities/'
      preLoaderRoute: typeof StudentActivitiesIndexRouteImport
      parentRoute: typeof StudentRouteRoute
    }
    '/student/activities/$missionId': {
      id: '/student/activities/$missionId'
      path: '/activities/$missionId'
      fullPath: '/student/activities/$missionId'
      preLoaderRoute: typeof StudentActivitiesMissionIdRouteImport
      parentRoute: typeof StudentRouteRoute
    }
    '/student/cafe/': {
      id: '/student/cafe/'
      path: '/cafe'
      fullPath: '/student/cafe/'
      preLoaderRoute: typeof StudentCafeIndexRouteImport
      parentRoute: typeof StudentRouteRoute
    }
    '/student/cafe/$groupId': {
      id: '/student/cafe/$groupId'
      path: '/cafe/$groupId'
      fullPath: '/student/cafe/$groupId'
      preLoaderRoute: typeof StudentCafeGroupIdRouteImport
      parentRoute: typeof StudentRouteRoute
    }
    '/student/missions/': {
      id: '/student/missions/'
      path: '/missions'
      fullPath: '/student/missions/'
      preLoaderRoute: typeof StudentMissionsIndexRouteImport
      parentRoute: typeof StudentRouteRoute
    }
    '/student/missions/$code': {
      id: '/student/missions/$code'
      path: '/missions/$code'
      fullPath: '/student/missions/$code'
      preLoaderRoute: typeof StudentMissionsCodeRouteImport
      parentRoute: typeof StudentRouteRoute
    }
    '/student/missions/$runId': {
      id: '/student/missions/$runId'
      path: '/missions/$runId'
      fullPath: '/student/missions/$runId'
      preLoaderRoute: typeof StudentMissionsRunIdRouteImport
      parentRoute: typeof StudentRouteRoute
    }
  }
}

interface InstructorRouteRouteChildren {
  InstructorCafeRoute: typeof InstructorCafeRoute
  InstructorDashboardRoute: typeof InstructorDashboardRoute
  InstructorDossierRoute: typeof InstructorDossierRoute
  InstructorEvaluationsRoute: typeof InstructorEvaluationsRoute
  InstructorFeaturesRoute: typeof InstructorFeaturesRoute
  InstructorFinalRoute: typeof InstructorFinalRoute
  InstructorGamificationRoute: typeof InstructorGamificationRoute
  InstructorGroupsRoute: typeof InstructorGroupsRoute
  InstructorInventoryRoute: typeof InstructorInventoryRoute
  InstructorPortfoliosRoute: typeof InstructorPortfoliosRoute
  InstructorProfileRoute: typeof InstructorProfileRoute
  InstructorQaRoute: typeof InstructorQaRoute
  InstructorRecoveryRoute: typeof InstructorRecoveryRoute
  InstructorReportsRoute: typeof InstructorReportsRoute
  InstructorClassesClassIdRoute: typeof InstructorClassesClassIdRoute
  InstructorMissionsMissionIdRoute: typeof InstructorMissionsMissionIdRoute
  InstructorStudentsStudentIdRoute: typeof InstructorStudentsStudentIdRoute
  InstructorClassesIndexRoute: typeof InstructorClassesIndexRoute
  InstructorMissionsIndexRoute: typeof InstructorMissionsIndexRoute
  InstructorStudentsIndexRoute: typeof InstructorStudentsIndexRoute
  InstructorSubmissionsIndexRoute: typeof InstructorSubmissionsIndexRoute
}

const InstructorRouteRouteChildren: InstructorRouteRouteChildren = {
  InstructorCafeRoute: InstructorCafeRoute,
  InstructorDashboardRoute: InstructorDashboardRoute,
  InstructorDossierRoute: InstructorDossierRoute,
  InstructorEvaluationsRoute: InstructorEvaluationsRoute,
  InstructorFeaturesRoute: InstructorFeaturesRoute,
  InstructorFinalRoute: InstructorFinalRoute,
  InstructorGamificationRoute: InstructorGamificationRoute,
  InstructorGroupsRoute: InstructorGroupsRoute,
  InstructorInventoryRoute: InstructorInventoryRoute,
  InstructorPortfoliosRoute: InstructorPortfoliosRoute,
  InstructorProfileRoute: InstructorProfileRoute,
  InstructorQaRoute: InstructorQaRoute,
  InstructorRecoveryRoute: InstructorRecoveryRoute,
  InstructorReportsRoute: InstructorReportsRoute,
  InstructorClassesClassIdRoute: InstructorClassesClassIdRoute,
  InstructorMissionsMissionIdRoute: InstructorMissionsMissionIdRoute,
  InstructorStudentsStudentIdRoute: InstructorStudentsStudentIdRoute,
  InstructorClassesIndexRoute: InstructorClassesIndexRoute,
  InstructorMissionsIndexRoute: InstructorMissionsIndexRoute,
  InstructorStudentsIndexRoute: InstructorStudentsIndexRoute,
  InstructorSubmissionsIndexRoute: InstructorSubmissionsIndexRoute,
}

const InstructorRouteRouteWithChildren = InstructorRouteRoute._addFileChildren(
  InstructorRouteRouteChildren,
)

interface StudentRouteRouteChildren {
  StudentDashboardRoute: typeof StudentDashboardRoute
  StudentEvaluationRoute: typeof StudentEvaluationRoute
  StudentEvidencesRoute: typeof StudentEvidencesRoute
  StudentInventoryRoute: typeof StudentInventoryRoute
  StudentJourneyRoute: typeof StudentJourneyRoute
  StudentPortfolioRoute: typeof StudentPortfolioRoute
  StudentProfileRoute: typeof StudentProfileRoute
  StudentProgressRoute: typeof StudentProgressRoute
  StudentQaRoute: typeof StudentQaRoute
  StudentRankingRoute: typeof StudentRankingRoute
  StudentRecordsRoute: typeof StudentRecordsRoute
  StudentActivitiesMissionIdRoute: typeof StudentActivitiesMissionIdRoute
  StudentCafeGroupIdRoute: typeof StudentCafeGroupIdRoute
  StudentMissionsCodeRoute: typeof StudentMissionsCodeRoute
  StudentMissionsRunIdRoute: typeof StudentMissionsRunIdRoute
  StudentActivitiesIndexRoute: typeof StudentActivitiesIndexRoute
  StudentCafeIndexRoute: typeof StudentCafeIndexRoute
  StudentMissionsIndexRoute: typeof StudentMissionsIndexRoute
}

const StudentRouteRouteChildren: StudentRouteRouteChildren = {
  StudentDashboardRoute: StudentDashboardRoute,
  StudentEvaluationRoute: StudentEvaluationRoute,
  StudentEvidencesRoute: StudentEvidencesRoute,
  StudentInventoryRoute: StudentInventoryRoute,
  StudentJourneyRoute: StudentJourneyRoute,
  StudentPortfolioRoute: StudentPortfolioRoute,
  StudentProfileRoute: StudentProfileRoute,
  StudentProgressRoute: StudentProgressRoute,
  StudentQaRoute: StudentQaRoute,
  StudentRankingRoute: StudentRankingRoute,
  StudentRecordsRoute: StudentRecordsRoute,
  StudentActivitiesMissionIdRoute: StudentActivitiesMissionIdRoute,
  StudentCafeGroupIdRoute: StudentCafeGroupIdRoute,
  StudentMissionsCodeRoute: StudentMissionsCodeRoute,
  StudentMissionsRunIdRoute: StudentMissionsRunIdRoute,
  StudentActivitiesIndexRoute: StudentActivitiesIndexRoute,
  StudentCafeIndexRoute: StudentCafeIndexRoute,
  StudentMissionsIndexRoute: StudentMissionsIndexRoute,
}

const StudentRouteRouteWithChildren = StudentRouteRoute._addFileChildren(
  StudentRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InstructorRouteRoute: InstructorRouteRouteWithChildren,
  StudentRouteRoute: StudentRouteRouteWithChildren,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
