/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InstructorRouteRouteImport } from './routes/instructor/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as StudentRouteRouteImport } from './routes/student/route'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as InstructorDashboardRouteImport } from './routes/instructor/dashboard'
import { Route as InstructorGroupsRouteImport } from './routes/instructor/groups'
import { Route as InstructorStudentsRouteImport } from './routes/instructor/students'
import { Route as InstructorClassesIndexRouteImport } from './routes/instructor/classes.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorRouteRoute = InstructorRouteRouteImport.update({
  id: '/instructor',
  path: '/instructor',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRouteRoute = StudentRouteRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorDashboardRoute = InstructorDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => InstructorRouteRoute,
} as any)
const InstructorGroupsRoute = InstructorGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => InstructorRouteRoute,
} as any)
const InstructorStudentsRoute = InstructorStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => InstructorRouteRoute,
} as any)
const InstructorClassesIndexRoute = InstructorClassesIndexRouteImport.update({
  id: '/classes/',
  path: '/classes/',
  getParentRoute: () => InstructorRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/instructor': typeof InstructorRouteRouteWithChildren
  '/student': typeof StudentRouteRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/instructor/dashboard': typeof InstructorDashboardRoute
  '/instructor/groups': typeof InstructorGroupsRoute
  '/instructor/students': typeof InstructorStudentsRoute
  '/instructor/classes/': typeof InstructorClassesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/instructor': typeof InstructorRouteRouteWithChildren
  '/student': typeof StudentRouteRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/instructor/dashboard': typeof InstructorDashboardRoute
  '/instructor/groups': typeof InstructorGroupsRoute
  '/instructor/students': typeof InstructorStudentsRoute
  '/instructor/classes': typeof InstructorClassesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/instructor': typeof InstructorRouteRouteWithChildren
  '/student': typeof StudentRouteRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/instructor/dashboard': typeof InstructorDashboardRoute
  '/instructor/groups': typeof InstructorGroupsRoute
  '/instructor/students': typeof InstructorStudentsRoute
  '/instructor/classes/': typeof InstructorClassesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/instructor'
    | '/student'
    | '/login'
    | '/reset-password'
    | '/auth/callback'
    | '/instructor/dashboard'
    | '/instructor/groups'
    | '/instructor/students'
    | '/instructor/classes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/instructor'
    | '/student'
    | '/login'
    | '/reset-password'
    | '/auth/callback'
    | '/instructor/dashboard'
    | '/instructor/groups'
    | '/instructor/students'
    | '/instructor/classes'
  id:
    | '__root__'
    | '/'
    | '/instructor'
    | '/student'
    | '/login'
    | '/reset-password'
    | '/auth/callback'
    | '/instructor/dashboard'
    | '/instructor/groups'
    | '/instructor/students'
    | '/instructor/classes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InstructorRouteRoute: typeof InstructorRouteRouteWithChildren
  StudentRouteRoute: typeof StudentRouteRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructor': {
      id: '/instructor'
      path: '/instructor'
      fullPath: '/instructor'
      preLoaderRoute: typeof InstructorRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructor/dashboard': {
      id: '/instructor/dashboard'
      path: '/dashboard'
      fullPath: '/instructor/dashboard'
      preLoaderRoute: typeof InstructorDashboardRouteImport
      parentRoute: typeof InstructorRouteRoute
    }
    '/instructor/groups': {
      id: '/instructor/groups'
      path: '/groups'
      fullPath: '/instructor/groups'
      preLoaderRoute: typeof InstructorGroupsRouteImport
      parentRoute: typeof InstructorRouteRoute
    }
    '/instructor/students': {
      id: '/instructor/students'
      path: '/students'
      fullPath: '/instructor/students'
      preLoaderRoute: typeof InstructorStudentsRouteImport
      parentRoute: typeof InstructorRouteRoute
    }
    '/instructor/classes/': {
      id: '/instructor/classes/'
      path: '/classes'
      fullPath: '/instructor/classes/'
      preLoaderRoute: typeof InstructorClassesIndexRouteImport
      parentRoute: typeof InstructorRouteRoute
    }
  }
}

interface InstructorRouteRouteChildren {
  InstructorDashboardRoute: typeof InstructorDashboardRoute
  InstructorGroupsRoute: typeof InstructorGroupsRoute
  InstructorStudentsRoute: typeof InstructorStudentsRoute
  InstructorClassesIndexRoute: typeof InstructorClassesIndexRoute
}

const InstructorRouteRouteChildren: InstructorRouteRouteChildren = {
  InstructorDashboardRoute: InstructorDashboardRoute,
  InstructorGroupsRoute: InstructorGroupsRoute,
  InstructorStudentsRoute: InstructorStudentsRoute,
  InstructorClassesIndexRoute: InstructorClassesIndexRoute,
}

const InstructorRouteRouteWithChildren = InstructorRouteRoute._addFileChildren(
  InstructorRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InstructorRouteRoute: InstructorRouteRouteWithChildren,
  StudentRouteRoute: StudentRouteRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
